### ISSUE TITLE
Remove the role names modification from the ProvisioningHandler level.

### ISSUE THREAD

**Issue by harsha1979** [wso2/carbon-identity-framework#1511]
**Description:**
Right we have remove the domain of the roles within the ProvisioningHandler level and because of that it is not allowed to add internal or application roles from the ProvisioningHandler extensions.

**Suggested Labels:**
We have already validated this user store domain within user store operation level and we don't need to do that from ProvisioningHandler level

**Suggested Assignees:**
darshana@wso2.com

**Affected Product Version:**
5.3.0,5.4.0,5.4.1,5.5.0   

**Steps to reproduce:**
Write an extended version of ProvisioningHandler and try to add an application role to the role list. Then it will throw an exception saying that role doesn't exist.

**Comment by malithie** [comment]
Only, internal roles with 'Application/' internal role domain and 'Workflow/' internal domain had been restricted as at now.

**Comment by malithie** [comment]
Need to support 'Application/*' and 'Workflow/*' type internal roles.
Moreover, when internal roles are mapped for the Identity Provider from the UI, role domain names are persisted with upper case.
For example adding a mapping for 'Application/testrole1' will persist the mapping as 'APPLICATION/testrole1'.
Then, at provisioning handler, the role mapped is checked against existing roles in the user store.
As the user store returns the above internal role domain in camel case as 'Application/testrole1', the respective role gets filtered out from the role list to be updated for the user.
