### ISSUE TITLE
Uppercase table identifiers are not working for PostgreSQL in DatabaseMetaData#getTables method

### ISSUE THREAD

**Issue by ChanakaCooray** [wso2/carbon-identity-framework#1641]
**Description:**
PostgreSQL is supported for LowerCaseIdentifiers. So following is not working when using with a PostgreSQL database.

```
DatabaseMetaData metaData = connection.getMetaData();
metaData.getTables(null, null, "IDN_ASSOCIATED_ID", new String[] { "TABLE" })

```
In PostgreSQL, we have to use as follows(Note the lowercase table identifier).

```
DatabaseMetaData metaData = connection.getMetaData();
metaData.getTables(null, null, "idn_associated_id", new String[] { "TABLE" })

```
But this will differ from database to database since some databases support for lowercase and some databases support for uppercase. So as a general solution, we need to first check how the database stores identifiers and then get the tables according to that. We can determine that using the following method calls.

```
meta.storesUpperCaseIdentifiers()
meta.storesLowerCaseIdentifiers()
meta.storesMixedCaseIdentifiers()
```
source : https://github.com/wso2/carbon-identity-framework/blob/master/components/user-mgt/org.wso2.carbon.identity.user.profile/src/main/java/org/wso2/carbon/identity/user/profile/mgt/internal/IdentityUserProfileServiceComponent.java#L126

**Suggested Labels:**
Bug

**Affected Product Version:**
v5.11.148

**OS, DB, other environment details and versions:**    
jdk1.8
Postgresql database

**Steps to reproduce:**
- Connect to a PostgreSQL database
- Start the server

**Comment by IndunilRathnayake** [comment]
Fixed with https://github.com/wso2/carbon-identity-framework/commit/a48393e9d1e3419e0ec8221a20b105bf074c9bb1
