### ISSUE TITLE
Account confirmation email template is not changing when using the old implementation of identity management.

### ISSUE THREAD

**Issue by LahiruLS** [wso2/carbon-identity-framework#2056]
**Description:**
Account confirmation email template is not changing when using the old implementation of identity management. The issue is that even if we change the email template for "AccountConfirmation", we are receiving some other email template. Also, if we change the relevant email template from the <IS_HOME>/repository/conf/email/email-admin-config.xml file but the issue still persists.

**Affected Product Version:**
WSO2 Identity Server 5.5.0

**Steps to reproduce:**

1. Configure the identity.xml file as described in the documentaion[1].
2. Configure the identity-mgt.properties file as the aforementioned documentation[1].
3. Configure the axis2.xml for the "mailto" TransportSender as explained in the aforementioned documentation[1].
4. Then restart the IS server and enabled the Self Registration.
5. Then create the user with the "UserInformationRecoveryService" admin service.
6. Check for the email I have received.

[1] - https://docs.wso2.com/display/IS520/Self+Sign+Up+and+Account+Confirmation

**Comment by LahiruLS** [comment]
I have debugged the issue and find out that the issue. It seems the email template is saving to the registry location "/_system/config/identity/email/accountconfirmation". But when loading the email template it loads from the location "/_system/config/identity/config/emailTemplate".
So as a workaround we can change the value of the property from the registry itself to overcome this issue. I have checked this and confirmed this scenario.

**Comment by johannesboon** [comment]
@LahiruLS I've got the same issue here. May I ask? How did you pull it off to change the email templates? 

I tried the carbon webapplication but discovered that if you try to edit them these template texts are put into an HTML text input, which removes all newlines upon submission and changing it to a textarea through Chrome Inspect is a bit of a pain.

Did you download and install the https://wso2.com/products/governance-registry/ and used its REST API? 

Or are there other ways to change the old email templates?

**Comment by LahiruLS** [comment]
@johannesboon this issue was only observed when the below event listener with orderId=50 is enabled from <IS-HOMES>/repository/conf/identity/identity.xml file and the event listners with orderId=95 and orderId=97 are disabled as below.
```
<EventListener type="org.wso2.carbon.user.core.listener.UserOperationEventListener"
                       name="org.wso2.carbon.identity.mgt.IdentityMgtEventListener"
                       orderId="50" enable="true"/>
        <EventListener type="org.wso2.carbon.user.core.listener.UserOperationEventListener"
                       name="org.wso2.carbon.identity.governance.listener.IdentityMgtEventListener"
                       orderId="95" enable="true"/>
        <EventListener type="org.wso2.carbon.user.core.listener.UserOperationEventListener" name="org.wso2.carbon.identity.governance.listener.IdentityStoreEventListener"
                       orderId="97" enable="true">
            <Property name="Data.Store">org.wso2.carbon.identity.governance.store.JDBCIdentityDataStore</Property>
        </EventListener>
```
You have to confirm if the issue you are observing is the same one as I observe. :)

When using the older implementation of identity event listeners (Currently you are using this) you need to enable the old menu items for changing the email template.

In order to address this issue in the first way I've mentioned earlier, please follow the below instructions.

- Open the file <IS_HOME>/repository/conf/carbon.xml

- Locate the tag <HideMenuItemIds> in this file.

It should be as below,
```
<HideMenuItemIds>
<HideMenuItemId>claim_mgt_menu</HideMenuItemId>
<HideMenuItemId>identity_mgt_emailtemplate_menu</HideMenuItemId>
<HideMenuItemId>identity_security_questions_menu</HideMenuItemId>
</HideMenuItemIds>
```

- Change it as below to enable the menu items of email template menu items for older implementation of identity event listeners.
```
<HideMenuItemIds>
<HideMenuItemId>claim_mgt_menu</HideMenuItemId>
<!--HideMenuItemId>identity_mgt_emailtemplate_menu</HideMenuItemId-->
<HideMenuItemId>identity_security_questions_menu</HideMenuItemId>
</HideMenuItemIds>
```

- Then restart the server.

- By using the UI navigate to the below path and change the templates from login into the management console via browser, 
Home -> Configure -> Email Templates
