### ISSUE TITLE
Allow disabling user consent page per-application

### ISSUE THREAD

**Issue by Kavindu-Dodan** [wso2/carbon-identity-framework#2202]
**Description:**
Currently, <SkipUserConsent>true</SkipUserConsent> in the identity.xml can be used to disable user consent page globally, which applies to all service providers across all tenants.

It is necessary to allow disabling user consent screen at service provider level.

**Comment by nilasini** [comment]
Duplicates https://github.com/wso2/carbon-identity-framework/issues/2202
